### ISSUE TITLE
Tests failing on i686

### ISSUE THREAD

**Issue by osteffenrh** [rust-osdev/endian-num#3]
Tests involving `usize` or `isize` fail on i686 (and probably other non-64bit platforms) due to conversion of 64bit literals.

For example:
```
error: literal out of range for `usize`
 --> src/lib.rs:1155:30
  |
8 | let m = Be::<usize>::from_ne(0xaa00000000006e1);
  |                              ^^^^^^^^^^^^^^^^^
  |
  = note: the literal `0xaa00000000006e1` (decimal `765611936652986081`) does not fit into the type `usize` and will become `1761usize`
  = note: `#[deny(overflowing_literals)]` on by default
```

I assume everything works fine still, because tests for `u64`/`i64` and bigger are passing.

**Comment by mkroening** [comment]
Ah, this makes sense. Thanks for opening an issue!

**Comment by osteffenrh** [comment]
Nice! Thanks fixing this so quickly.
